engines:
  eslint:
    enabled: true
  csslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - javascript:
        mass_threshold: 99
  fixme:
    enabled: true
  nodesecurity:
    enabled: true
ratings:
  paths:
  - src/client/**
  - src/commom/**
  - src/server/**
  - "**.js"
exclude_paths:
- "**/vendor/**/*"
- "**/node_modules/**/*"
- "**/bower_components/**/*"
- src/client/js/lb-services.js
